name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Bats and Bats libraries
      uses: bats-core/bats-action@2.0.0      
    - name: Build and run tests
      run: bats -T test
