name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup BATS
      uses: mig4/setup-bats@v1.2.0
      
    - name: Build and Test Docker Image
      uses: actions/checkout@v4
      run: bats -T .test/validation_tests.bats
